trigger: none

resources:
  containers:
  - container: petclinic-ado
    image: mtritabaugh/petclinic:latest
    endpoint: dockerhub
    mapDockerSocket: true
    mountReadOnly: 
      externals: false
      tasks: false
      tools: false
      work: false
    trigger: 
      enabled: true
        include: '*'

stages:
- stage: 'TEST'
  jobs:
  - job: 'test_job'
    steps:
      - script: echo 'hello'
