trigger: none

resources:
  containers:
  - container: petclinic-ado
    image: mtritabaugh/petclinic
    endpoint: dockerhub
    env: {}
    ports: 8080
    volumes: /tmp/test
    mapDockerSocket: true
    mountReadOnly: 
      externals: false
      tasks: false
      tools: false
      work: false

